# Generated by Django 4.1.7 on 2023-02-24 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMobilkinApp', '0002_alter_modelcargeneration_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
